# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55c6f615908119a8634a5082b1b2a720"
name = "product-editor"
application_url = "https://shopify-product-editor-u8dw.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify-product-editor-u8dw.onrender.com/auth/callback" ]
